dist: trusty

language: python
matrix:
  include:
  - os: linux
    python: 2.7
    env: BUILD=PYPI
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
  - os: linux
    python: 3.7
    dist: xenial
    sudo: true
  - os: linux
    python: 3.8
    dist: xenial
    sudo: true

install:
- pip install --upgrade pip==19.1
- pip install -r requirements/test.txt
- pip install -r requirements/sdk.txt
- pip install pytest-cov

script:
- flake8 connect
- pytest --cov-report=xml --cov=./connect
- sed -i "s/version='0.0.0'/version='${TRAVIS_TAG}'/g" setup.py
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'

after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "cloudbluesonarcube"
    token:
      secure: rLMrKhQitMly/RhNQp0ixxQwVIuRpFY1ruKprZ2LSmE+RD3guFxtZ+EMX12gSdOBd3vV4qUfPKAcFThFDjNAscP6W3rcxip85pPWV8QiCjm0mszIlQiU7GjyMq0gOf5pLDTQk67gTBDkpXBVpPv4BgEfG2ms5BLMvkGmCba+4iRa8QQ2J0OaRV69DuOnOftc4YZZnJeVNxfm+OrRInDfmcdJfOAChWzmjsriHATu4KbV9r1G7zMkU0ovvLavS8pqg6PEu5lYbFAYa2O1wG/sRTufIPqCSbQvK6gwzsFbwFtfshWHz1MAMhVub0cVWj+umXab3o+Av1bqNMC3xrzzL05PJSpCExBXrHhdsS/I7ucXSmOiJZhu69HZvoaujbaYmTFGHz/BUdvFrNNIEXKAQOo/N2bnlGpzOora1QFJRX05yx9y5/Z6T+qOJ1uVp3JyoOtw4xkrbeU2AWQko04whN6FJ6ljHlfoubGwdme7Sz7JsGkEFxBHSLyZX9QNtUKnq6vAZEMJmiVtiCNes+f7gCH8h92Jyw0zD5tNxYrvZJS5w235CV88G1FLLG1Kl6eegj+EompH4vlf2kXDEEVzGzzDHjROC6LzUMuxABmeJ/lkxzrfKi5P7R5JbQzWKBjyzMRLneD0pwJWePLmMr2zGA9f75S1th4yqvr+NzjbQrA=
deploy:
  skip_cleanup: true
  provider: pypi
  user: apslite
  password:
    secure: nzWd7Fqgi/K5YKqrAPkIBkgRImWQyQgD2/qP3fYksyJnIFWNcea5T4EKqQKXIPZHh1K0cRhT7mSjIfIrQ6H3XKM/eMTAlz6pbisG2cuu4ueUBjbxHCVCkwzBPgF7+DuCJUXJ/SHyoqMnTdAQo8fb8g69/UCmnUp37YoDO1YHXIMjFVkNc6PFS7nQElXnWkvWd1SpQgA1ZdWdwBzEnIiq+L6IFeTa83PH0Schkem/vR9Ql9CmuliovNt3yHfFaeIqLUgOmsfrwOtDVs0/SkcF+Gg5tNds7DHH2TR4fHco5s8F+n4FVgv2DUPlvBbOVvUH1RiRB8hdATetUxe1cU8fT1nPdJASLWS5E4b4knGLH53+bGxqPVezHxghbVYZHPXp7yI1zWX/Wtn9MBiAo9S3f+Tf8zTk5PIjAJLG/Sdn0RX8mLn89fsslku3enH/FknwPtG+xVYSzUlrd+yzHKnqYkKJzMjsBq/F5+shmYSDlnGdGv+Ga3xZSjIoXlphO5qpxR7vrGnLMxEPJC06+mPgPZp1qfDMyrei/IAPRP8qYPC+Vnj8yclH/UyBKT66z2UEP1z5Op99fUXi3W59x2zdVaLHYniNf16UqtrE5kc7gdLvVcH+NtbO716SAbvO5ql/JsYYTmDSoWEC9KWZS+4E7p7n45c8DEieg8Q5HThWF9Y=
  on:
    tags: true
    all_branches: true
    distributions: sdist
    condition: "$BUILD = PYPI"
